<?php
// Generated by Zend Framework 2
return array(
    'GeonamesServer\Module'                       => __DIR__ . '//Module.php',
    'GeonamesServer\Controller\ApiController'     => __DIR__ . '//src/GeonamesServer/Controller/ApiController.php',
    'GeonamesServer\Controller\ConsoleController' => __DIR__ . '//src/GeonamesServer/Controller/ConsoleController.php',
    'GeonamesServer\Controller\DemoController'    => __DIR__ . '//src/GeonamesServer/Controller/DemoController.php',
    'GeonamesServer\Service\Elasticsearch'        => __DIR__ . '//src/GeonamesServer/Service/Elasticsearch.php',
    'GeonamesServer\Service\Installer'            => __DIR__ . '//src/GeonamesServer/Service/Installer.php',
);